-- WORKBOOK-FUNCTION 문제풀이
-- 3. 남자 교수 이름 나이(나이의 오름차순 정렬) 조회
SELECT PROFESSOR_NAME
            , EXTRACT(YEAR FROM SYSDATE) - (19 || SUBSTR(PROFESSOR_SSN,1,2)) 나이
FROM TB_PROFESSOR
WHERE SUBSTR(PROFESSOR_SSN,8,1) IN ('1','3')
ORDER BY 나이;

-- 13. 학과별 휴학생 수(학과번호, 휴학생 수)
SELECT DEPARTMENT_NO 학과번호, COUNT(DECODE(ABSENCE_YN, 'Y',1)) "휴학생 수"
   FROM TB_STUDENT
 GROUP BY DEPARTMENT_NO
 ORDER BY 학과번호;
 
 SELECT STUDENT_NAME FROM TB_STUDENT
WHERE DEPARTMENT_NO = '001'
AND ABSENCE_YN = 'Y' AND SUBSTR(STUDENT_SSN, 8, 1) = '2';