-- SELECT



-- FUNCTION
-- 3. 남자 교수 이름 나이 (나이의 오름차순 정렬) 조회
SELECT PROFESSOR_NAME,
        EXTRACT(YEAR FROM SYSDATE)-(19||SUBSTR(PROFESSOR_SSN, 1,2)) "나이"
FROM  TB_PROFESSOR
WHERE SUBSTR(PROFESSOR_SSN,8,1) IN('1','3')
ORDER BY 나이;